# Generated by Django 5.2.8 on 2025-11-22 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Car_service", "0002_alter_car_owner"),
    ]

    operations = [
        migrations.AlterField(
            model_name="seller",
            name="seller_license",
            field=models.CharField(max_length=120, unique=True),
        ),
    ]
