# Generated by Django 5.2.8 on 2025-11-22 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Car_service", "0004_alter_car_manufacturer_alter_car_owner"),
    ]

    operations = [
        migrations.AddField(
            model_name="car",
            name="price",
            field=models.IntegerField(default=0),
        ),
    ]
