# Generated by Django 5.2.8 on 2025-11-22 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Car_service", "0005_car_price"),
    ]

    operations = [
        migrations.AlterField(
            model_name="car",
            name="price",
            field=models.IntegerField(),
        ),
    ]
