# Generated by Django 5.2.8 on 2025-11-22 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Car_service", "0006_alter_car_price"),
    ]

    operations = [
        migrations.AddField(
            model_name="car",
            name="comment",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
