# Generated by Django 5.2.8 on 2025-11-24 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Car_service", "0007_car_comment"),
    ]

    operations = [
        migrations.AlterField(
            model_name="manufacturer",
            name="name",
            field=models.CharField(max_length=120, unique=True),
        ),
    ]
